 
spring:
  application:
    name: polling-app-server

  datasource:
    # UPDATE THE PASSWORD BELOW TO YOUR REAL LOCAL MYSQL PASSWORD
    # If your password is just 'root' or empty, change it here.
    url: ${DB_URL:jdbc:mysql://localhost:3306/PollingAPP?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:9479452076@Nw}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        # Fixed: Changed from MySQL8Dialect to MySQLDialect to stop the warning
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000

  cors:
    allowedOrigins: ${APP_CORS_ALLOWEDORIGINS:http://localhost:3000}
